language: python
python:
  - "3.6"
  - "nightly"
env:
  - PYTHONPATH=$PYTHONPATH:$(pwd)
install:
  - pip install -r requirements.txt
  - pip install pep8
script:
  - pep8 . --max-line-length=119
  - cd tests
  - pytest
matrix:
  fast_finish: true
  allow_failures:
    - python: "nightly"
notifications:
  email: false